version: '3.9'

services:
  profile-postgres:
    image: postgres:16
    container_name: profile-postgres
    environment:
      POSTGRES_DB: profiledb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - profile_pg_data:/var/lib/postgresql/data
    networks:
      - profile-net


volumes:
  profile_pg_data:

networks:
  profile-net:
    driver: bridge